
[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[[mouse.bindings]]
action = "ExpandSelection"
mouse = "Right"

[selection]
save_to_clipboard = true

[window]
decorations = "None"
dynamic_title = true
opacity = 0.8
blur = true
startup_mode = "Windowed"

[window.class]
general = "scratchpad"
instance = "scratchpad"

[window.padding]
x = 25
y = 25

[scrolling]
history = 10000
multiplier = 3

[general]
live_config_reload = true
import = ["/home/jampietro/.config/alacritty/colorschemes/catppuccin-mocha.toml", "/home/jampietro/.config/alacritty/fonts.toml"]
